name = "Test Modpack A"
author = "CinnamonBunniy"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "932adfde0707b1d36d06fbf526dedeaee6ea1cb88745d684b1f19333201ae952"

[versions]
fabric = "0.17.3"
minecraft = "1.21.1"
